/*
 * DotAAS Part 2 | HTTP/REST | Registry and Discovery
 * The registry and discovery interface as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: Final-Draft
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.catenax.semantics.framework.aas.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets KeyElements
 */
public enum KeyElements {
  ASSETADMINISTRATIONSHELL("AssetAdministrationShell"),
  ACCESSPERMISSIONRULE("AccessPermissionRule"),
  CONCEPTDESCRIPTION("ConceptDescription"),
  SUBMODEL("Submodel"),
  ANNOTATEDRELATIONSHIPELEMENT("AnnotatedRelationshipElement"),
  BASICEVENT("BasicEvent"),
  BLOB("Blob"),
  CAPABILITY("Capability"),
  DATAELEMENT("DataElement"),
  FILE("File"),
  ENTITY("Entity"),
  EVENT("Event"),
  MULTILANGUAGEPROPERTY("MultiLanguageProperty"),
  OPERATION("Operation"),
  PROPERTY("Property"),
  RANGE("Range"),
  REFERENCEELEMENT("ReferenceElement"),
  RELATIONSHIPELEMENT("RelationshipElement"),
  SUBMODELELEMENT("SubmodelElement"),
  SUBMODELELEMENTLIST("SubmodelElementList"),
  SUBMODELELEMENTSTRUCT("SubmodelElementStruct"),
  VIEW("View"),
  FRAGMENTREFERENCE("FragmentReference");

  private String value;

  KeyElements(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static KeyElements fromValue(String input) {
    for (KeyElements b : KeyElements.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
