/*
 * DotAAS Part 2 | HTTP/REST | Registry and Discovery
 * The registry and discovery interface as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: Final-Draft
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.catenax.semantics.framework.aas.model;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * OneOfReference
 */
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NONE,
        defaultImpl = GlobalReference.class,
        property = "type")
@JsonSubTypes({
        @JsonSubTypes.Type(value = GlobalReference.class, name = "GlobalReference")
})
@JsonDeserialize(as=GlobalReference.class)
public interface OneOfReference {

}
