apiVersion: v1
kind: ConfigMap
metadata:
  name: simplescheduler
  namespace: centralconnector
data:
  application-resources.yml: |-
    scheduler:
      # resources map contains pairs of: (consumer resourceId) -> (producer URL)
      resources:
        195bf4c7-53e8-4438-8239-29df95365c2b: https://$CATENA_SERVICE_URL/partsmasterconnector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplescheduler
  namespace: centralconnector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplescheduler
  template:
    metadata:
      labels:
        app: simplescheduler
    spec:
      containers:
        - name: simplescheduler
          image: $CONTAINER_REGISTRY/simplescheduler:$VERSION
          env:
            - name: _JAVA_OPTIONS
              value: -Dspring.config.location=classpath:/,config/
            - name: SERVER_PORT
              value: "8081"
            - name: SCHEDULER_CRON
              value: "@hourly"
            - name: CONNECTOR_URL
              value: "https://$CATENA_SERVICE_URL/kmuconnector"
            - name: CONNECTOR_LOGIN
              valueFrom:
                secretKeyRef:
                  key: connector_login
                  name: simplescheduler-secret
            - name: CONNECTOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: connector_password
                  name: simplescheduler-secret
            - name: LOGGING_LEVEL
              value: "DEBUG"
          volumeMounts:
            - name: configuration
              mountPath: /config
              readOnly: true
          ports:
            - containerPort: 8081
      volumes:
        - name: configuration
          configMap:
            name: simplescheduler
            items:
              - key: application-resources.yml
                path: application-resources.yml
---
apiVersion: v1
kind: Service
metadata:
  name: simplescheduler
  namespace: centralconnector
spec:
  type: ClusterIP
  ports:
    - port: 8081
  selector:
    app: simplescheduler