apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prs-ingress

spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: prs
                port:
                  number: 80
          - path: /swagger-ui
            pathType: Prefix
            backend:
              service:
                name: prs
                port:
                  number: 80